Repository ucsb-cs156-f23/proj-courses-f23-7pm-3, pull requests merged in 2023-11, with the labels that each got.

#29 Bugfix: Searching for a TA makes the first section appear as a lecture
  frontend/src/main/components/Sections/SectionsInstructorTable.js
  frontend/src/main/components/SectionsInstructorTableBase.js
  frontend/src/main/pages/CourseOverTime/CourseOverTimeInstructorIndexPage.js
  frontend/src/stories/components/Sections/SectionInstructorTable.stories.js
  frontend/src/stories/components/SectionsInstructorTableBase.stories.js
  frontend/src/tests/components/Sections/SectionsInstructorTable.test.js
  frontend/src/tests/components/SectionsInstructorTableBase.test.js
Labels: 10

#32 Added CourseDetailsTable Component and Test
  frontend/src/fixtures/courseDetailsFixtures.js
  frontend/src/main/components/CourseDetails/CourseDetailsTable.js
  frontend/src/stories/components/CourseDetails/CourseDetailsTable.stories.js
  frontend/src/tests/components/CourseDetailsTable.test.js/CourseDetailsTable.test.js
Labels: 10

#36 Refactoring Code
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeInstructorController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeBuildingControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeInstructorControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBSectionsControllerTests.java
Labels: 5, Merge Candidate

#38 Add Button Column
  frontend/src/main/components/Sections/SectionsOverTimeTable.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsOverTimeTable.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 10, Merge Candidate

#40 Added Course Dropdown Menu for Personal Schedules
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/pages/Courses/PSCourseCreatePage.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
Labels: 10, Merge Candidate

#41 Add General Search to Dropdown
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/SectionSearches/SectionSearchesIndexPage.js
Labels: 5, Merge Candidate

#42 Fixed typo in footer
  frontend/src/main/components/Nav/Footer.js
Labels: 5, Merge Candidate
